### ISSUE TITLE
スペルミス

### ISSUE THREAD

**Issue by haduki1208** [Getsu/react-todoapp#1]
https://github.com/Getsu/react-todoapp/blob/b3b948c23907937167a802a92d0005c805feeac5/src/App.js#L14-L15

https://github.com/Getsu/react-todoapp/blob/b3b948c23907937167a802a92d0005c805feeac5/src/App.js#L25

スペルミスとキャメルケースが抜けている部分があります。
vscodeの拡張でスペルチェックができるので導入してみてください。
![image](https://user-images.githubusercontent.com/22188454/102774717-e2a94480-43ce-11eb-819e-3b31b549f8fb.png)
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

**Comment by Getsu** [comment]
スペルミスを修正し拡張機能を導入しました。
[08c6ad2b5405461d4886634c230681a41f7e0361](url)

**Comment by haduki1208** [comment]
![LGTM](https://cdn.lgtmoon.dev/images/81315)
