### ISSUE TITLE
使用していない変数がある

### ISSUE THREAD

**Issue by haduki1208** [Getsu/react-todoapp#3]
https://github.com/Getsu/react-todoapp/blob/b3b948c23907937167a802a92d0005c805feeac5/src/TodoElement.js#L2

`{ Component }`が使用されていない。削除するか、使用するかのどちらかに修正してください。

**Comment by Getsu** [comment]
{ Component } を削除しました。971fccc6acd6137679ef9c4810181e66295e753f

**Comment by haduki1208** [comment]
![LGTM](https://cdn.lgtmoon.dev/images/81315)
